### PR TITLE
security token is now mandatory

### PR DESCRIPTION
**Pull request by claymccoy**
if the auth server base url is supplied, then a token is required. It was optional for backward compatibility while all our usages moved to the dashboard UI.

### CODE REVIEW

**Comment by claymccoy** [comment]
fixes #7

**Comment by cdupuis** [comment]
> security token is no longer mandatory

title says _no longer mandatory_???

**Comment by claymccoy** [comment]
that was a mistake, fixed

**Comment by claymccoy** [comment]
force pushed just to change the commit message

**Comment by claymccoy** [comment]
Of course, the build failed when trying "npm run build"
I'll fix that later.  It builds just fine with Maven.

**Comment by cdupuis** [comment]
I was wondering why the SDM event builds this, but it is a node project too. Or rather it has a `package.json`.

**Comment by claymccoy** [comment]
Oh, that makes sense. :) 
But we let the Maven build the JS with a plugin.

**Pull request merged**
